services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: instaloader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:rw
      - ./sessions:/data/session:ro
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
